#! /bin/bash

dir="$(dirname "$0")"
deps="${dir}/packages/deps.list"

function check_fail {
  EXITSTATUS=$1
  if [[ $EXITSTATUS != 0 ]]; then
    show_error "Error code received. Exiting."
    sleep 3s && main
  fi
}

function install_dependencies {
  show_info "Checking dependencies."
  for package in $(cat $deps); do
    if ! pacman -Qi ${package} > /dev/null 2>&1; then
      show_info "${package} is needed for this script."
      sudo pacman -S ${package}
      check_fail
      show_success "${package} now installed."
    else
      show_success "${package} is already installed."
    fi
  done
}

function check_network {
  show_info "Checking network connection."
  wget -q --tries=10 --timeout=20 --spider https://google.com
  if ! [[ $? -eq 0 ]]; then
    show_error "Cannot start network connextion."
    show_info "Trying dhcpcd unit."
    if [[ $(systemctl is-active dncpcd) == "active" ]]; then
      show_error "dhcpcd is already active. Exiting."
      exit 1
    else
      sudo systemctl start dhcpcd
      show_info "Sleep a bit to wait for network interface to finish loading."
      sleep 10s
      wget -q --tries=10 --timeout=20 --spider https://google.com
      if ! [[ $? -eq 0 ]]; then
        show_error "Cannot start network connextion. Giving up."
        exit 1
      fi
    fi
  else
    show_success "Network is working."
  fi
}
