#! /bin/bash
set -eu

dir="$(dirname "$0")"

base="$dir/data/base.list"
toprc="$dir/dotfiles/toprc"
function install_base {
  show_info "Installing base packages."
  sudo pacman -S $(cat $base)
  check_fail
  show_success "Base packages installed."

  show_info "Installing toprc."
  cp -r $toprc $HOME/.toprc
  show_success "Installed toprc."

  show_info "Enable sudo insults."
  sudo visudo # Consider using another sed script (DANGEROUS!!!)
  sudo sed -i "/^CheckSpace$/a Color" /etc/pacman.conf
  sudo sed -i "/^CheckSpace$/a ILoveCandy" /etc/pacman.conf
}
