#! /bin/bash

# Arch Linux (post-)install scripts
# Copyright (C) 2020
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

DIR="$(dirname "$0")"

MKSDBOOTCONF="${DIR}/utils/sdboot-mkconfig"

function install_zsh {
  local zsh="${DIR}/packages/zsh.list"
  local zshrc="${DIR}/dotfiles/zshrc"
  local p10krc="${DIR}/dotfiles/p10k"

  show_header "Installing zsh."
  check_installed "${zsh}"
  show_success "zsh installed."

  mkdir -p "${HOME}/.local/share/zsh/site-functions"

  copy_config_file "${zshrc}" "${HOME}/.zshrc"
  copy_config_file "${p10krc}" "${HOME}/.p10k.zsh"

  if ! [ -d /etc/fonts/conf.d ]; then
    show_warning "'/etc/fonts/conf.d' for fontconfig is missing. Skipping."
  elif ! [ -e /etc/fonts/conf.d/10-nerd-font-symbols.conf ] &&
         [ -e /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf ]; then
    sudo ln -s \
      /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf \
      /etc/fonts/conf.d/
  fi
}

function install_linux_hardened {
  local hardened="${DIR}/packages/hardened.list"
  local hardenedsdadd="${DIR}/hooks/999-add-linux-hardened.hook"
  local hardenedsdremove="${DIR}/hooks/999-remove-linux-hardened.hook"
  local hardenedsdupdate="${DIR}/hooks/999-update-linux-hardened.hook"
  local pacmanhookdir="/etc/pacman.d/hooks"

  show_header "Installing linux-hardened kernel."
  check_installed "${hardened}"
  show_success "Hardened kernel installed."

  if command -v grub-mkconfig > /dev/null 2>&1; then
    show_info "Regenerating grub.cfg"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [[ "$(sudo bootctl is-installed)" = yes ]]; then
    sudo cp -af "${hardenedsdadd}" "${pacmanhookdir}"
    sudo cp -af "${hardenedsdremove}" "${pacmanhookdir}"
    sudo cp -af "${hardenedsdupdate}" "${pacmanhookdir}"
    sudo "${MKSDBOOTCONF}" linux-hardened
  fi
}

function install_linux_lts {
  local lts="${DIR}/packages/lts.list"
  local ltssdadd="${DIR}/hooks/999-add-linux-lts.hook"
  local ltssdremove="${DIR}/hooks/999-remove-linux-lts.hook"
  local ltssdupdate="${DIR}/hooks/999-update-linux-lts.hook"
  local pacmanhookdir="/etc/pacman.d/hooks"

  show_header "Installing linux-lts kernel."
  check_installed "${lts}"
  show_success "LTS kernel installed."

  if command -v grub-mkconfig > /dev/null 2>&1; then
    show_info "Regenerating grub.cfg"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [[ "$(sudo bootctl is-installed)" = yes ]]; then
    sudo cp -af "${ltssdadd}" "${pacmanhookdir}"
    sudo cp -af "${ltssdremove}" "${pacmanhookdir}"
    sudo cp -af "${ltssdupdate}" "${pacmanhookdir}"
    sudo "${MKSDBOOTCONF}" linux-lts
  fi
}

function install_linux_zen {
  local zen="${DIR}/packages/zen.list"
  local zensdadd="${DIR}/hooks/999-add-linux-zen.hook"
  local zensdremove="${DIR}/hooks/999-remove-linux-zen.hook"
  local zensdupdate="${DIR}/hooks/999-update-linux-zen.hook"
  local pacmanhookdir="/etc/pacman.d/hooks"

  show_header "Installing linux-zen kernel."
  check_installed "${zen}"
  show_success "Zen kernel installed."

  if command -v grub-mkconfig > /dev/null 2>&1; then
    show_info "Regenerating grub.cfg"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [[ "$(sudo bootctl is-installed)" = yes ]]; then
    sudo cp -af "${zensdadd}" "${pacmanhookdir}"
    sudo cp -af "${zensdremove}" "${pacmanhookdir}"
    sudo cp -af "${zensdupdate}" "${pacmanhookdir}"
    sudo "${MKSDBOOTCONF}" linux-zen
  fi
}

function install_linux_rt {
  local rt="${DIR}/packages/rt.list"
  local rtsdadd="${DIR}/hooks/999-add-linux-rt.hook"
  local rtsdremove="${DIR}/hooks/999-remove-linux-rt.hook"
  local rtsdupdate="${DIR}/hooks/999-update-linux-rt.hook"
  local pacmanhookdir="/etc/pacman.d/hooks"

  show_header "Installing linux-rt kernel."
  check_installed "${rt}"
  show_success "Zen kernel installed."
  show_success "Real-time kernel installed."

  if command -v grub-mkconfig > /dev/null 2>&1; then
    show_info "Regenerating grub.cfg"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [[ "$(sudo bootctl is-installed)" = yes ]]; then
    sudo cp -af "${rtsdadd}" "${pacmanhookdir}"
    sudo cp -af "${rtsdremove}" "${pacmanhookdir}"
    sudo cp -af "${rtsdupdate}" "${pacmanhookdir}"
    sudo "${MKSDBOOTCONF}" linux-rt
  fi
}

function install_linux_rt_lts {
  local rtlts="${DIR}/packages/rt-lts.list"
  local rtltssdadd="${DIR}/hooks/999-add-linux-rt-lts.hook"
  local rtltssdremove="${DIR}/hooks/999-remove-linux-rt-lts.hook"
  local rtltssdupdate="${DIR}/hooks/999-update-linux-rt-lts.hook"
  local pacmanhookdir="/etc/pacman.d/hooks"

  show_header "Installing linux-rt-lts kernel."
  check_installed "${rtlts}"
  show_success "Real-time LTS kernel installed."

  if command -v grub-mkconfig > /dev/null 2>&1; then
    show_info "Regenerating grub.cfg"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [[ "$(sudo bootctl is-installed)" = yes ]]; then
    sudo cp -af "${rtltssdadd}" "${pacmanhookdir}"
    sudo cp -af "${rtltssdremove}" "${pacmanhookdir}"
    sudo cp -af "${rtltssdupdate}" "${pacmanhookdir}"
    sudo "${MKSDBOOTCONF}" linux-rt-lts
  fi
}

function install_utils {
  local utils="${DIR}/packages/utils.list"
  local tmuxconfig="${DIR}/dotfiles/tmux.conf"
  local rkhunterconfig="/etc/rkhunter.conf"

  show_header "Installing general utilities."
  check_installed "${utils}"
  show_success "Utilities installed."

  show_info "Installing tmux config."
  cp -f "${tmuxconfig}" "${HOME}/.tmux.conf"

  show_info "Whitelisting files in /etc/rkhunter.conf"
  sudo sed -i \
    -e "/^#SCRIPTWHITELIST=\/usr\/bin\/groups$/a SCRIPTWHITELIST=\/usr\/bin\/egrep" \
    -e "/^#SCRIPTWHITELIST=\/usr\/bin\/groups$/a SCRIPTWHITELIST=\/usr\/bin\/fgrep" \
    -e "/^#SCRIPTWHITELIST=\/usr\/bin\/groups$/a SCRIPTWHITELIST=\/usr\/bin\/ldd" \
    -e "/^#SCRIPTWHITELIST=\/usr\/bin\/groups$/a SCRIPTWHITELIST=\/usr\/bin\/vendor_perl\/GET" \
    "${rkhunterconfig}"
}

function install_laptop {
  local laptop="${DIR}/packages/laptop.list"

  show_header "Installing laptop utilities."
  check_installed "${laptop}"
  show_success "Laptop utilities installed."

  # Enable tlp on laptops.
  show_info "Enabling and starting tlp systemd units."
  sudo systemctl enable tlp.service
  sudo systemctl start tlp.service
  show_success "tlp enabled."
}

function install_plymouth {
  local plymouth="${DIR}/packages/plymouth.list"
  local plymouthkde="${DIR}/packages/plymouth-kde.list"
  local mkinitcpioconf="/etc/mkinitcpio.conf"
  local grubconf="/etc/default/grub"

  show_header "Installing Plymouth splash screen."
  check_installed "${plymouth}"
  show_success "Plymouth installed."

  if pacman -Qi plasma-desktop > /dev/null 2>&1; then
    show_header "KDE Plasma installed. Installing Plymouth integration."
    check_installed "${plymouthkde}"
    show_success "Plymouth integration installed."
  fi

  show_info "Enabling Plymouth in mkinitcpio.conf."
  if ! grep -q "^HOOKS=(.*plymouth.*)$" "${mkinitcpioconf}"; then
    # Insert the Plymouth hook after kernel mode setting.
    sudo sed -i '/^HOOKS=/s/ kms / kms plymouth /' "${mkinitcpioconf}"
    sudo mkinitcpio -P
  fi

  if [ -f "${grubconf}" ] && ! sudo grep -q "^GRUB_CMDLINE_LINUX_DEFAULT=.*splash" "${grubconf}"; then
    show_info "Updating GRUB defaults for splash screen."
    sudo sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=/s/"$/ splash"/g' "${grubconf}"
    sudo grub-mkconfig -o /boot/grub/grub.cfg
  fi

  if [ "$(sudo bootctl is-installed)" = yes ]; then
    show_info "Updating Gummiboot entries for Plymouth splash screen."
    local efidir
    local conf
    efidir="$(bootctl -p)"
    while read -r conf; do
      if ! grep -q "^options.*splash" "${conf}"; then
        sudo sed -i "/^options/s/$/ splash/" "${conf}"
      fi
    done < <(sudo find "${efidir}"/loader/entries/ -name "*.conf")
  fi
}

function 01-misc {
  show_question "Misc: what do you want to install?"
  show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"

  local options=(
    "Back"
    "All"
    "Linux hardened kernel"
    "Linux LTS kernel"
    "Linux RT kernel"
    "Linux RT LTS kernel"
    "Linux zen kernel"
    "Linux utilities"
    "Laptop tools"
    "Plymouth"
    "zsh")
  local option
  select option in "${options[@]}"; do
    case "${option}" in
      "Back")
        break
        ;;
      "All")
        install_linux_hardened
        install_linux_lts
        install_linux_rt
        install_linux_rt_lts
        install_linux_zen
        install_utils
        install_laptop
        install_plymouth
        install_zsh
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux hardened kernel")
        install_linux_hardened
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux LTS kernel")
        install_linux_lts
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux RT kernel")
        install_linux_rt
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux RT LTS kernel")
        install_linux_rt_lts
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux zen kernel")
        install_linux_zen
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Linux utilities")
        install_utils
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Laptop tools")
        install_laptop
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "Plymouth")
        install_plymouth
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      "zsh")
        install_zsh
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        show_info "Main\n ${ENDBRANCH} Misc (Hit ENTER to see options again.)"
        ;;
    esac
  done
}
