#! /bin/bash
#set -eu

dir="$(dirname "$0")"

zsh="${dir}/packages/zsh.list"
zshrc="${dir}/dotfiles/zshrc"
zshdir="${HOME}/.zsh"
function install_zsh {
  show_info "Installing zsh."
  sudo pacman -S $(cat ${zsh})
  check_fail
  show_success "zsh installed."

  show_info "Downloading zsh extras."
  mkdir -p ${zshdir}
  git clone https://github.com/zsh-users/zsh-history-substring-search ${zshdir}/zsh-history-substring-search
  git clone https://github.com/zsh-users/zsh-autosuggestions ${zshdir}/zsh-autosuggestions

  show_info "Copying zshrc."
  cp -f ${zshrc} ${HOME}/.zshrc

  show_info "Changing login shell to zsh. Provide your password."
  chsh -s /bin/zsh
}

grsec="${dir}/packages/grsec.list"
function install_grsec {
  show_info "Installing grsecurity."
  sudo pacman -S $(cat ${grsec})
  check_fail
  show_success "Grsecurity-patched kernel installed."
  # need to set pax rules or enable learning mode
}

utils="${dir}/packages/utils.list"
function install_utils {
  show_info "Installing general utilities."
  sudo pacman -S $(cat ${utils})
  check_fail
  show_success "Utilities installed."
}

laptop="${dir}/packages/laptop.list"
function install_laptop {
  show_info "Installing laptop utilities."
  sudo pacman -S $(cat ${laptop})
  check_fail
  show_success "Laptop utilities installed."

  # Enable tlp on laptops.
  show_info "Enabling and starting tlp systemd units."
  sudo systemctl enable tlp.service
  sudo systemctl start tlp.service
  sudo systemctl enable tlp-sleep.service
  sudo systemctl start tlp-sleep.service
  show_success "tlp enabled."
}

android="${dir}/packages/android.list"
function install_android {
  show_info "Installing tools for Android devices."
  sudo pacman -S $(cat ${android})
  check_fail
  show_success "Android tools installed."
}
