#! /bin/bash
set -eu

dir="$(dirname "$0")"

zsh="${dir}/data/zsh.list"
zshrc="${dir}/dotfiles/zshrc"
function install_zsh {
  show_info "Installing zsh."
  sudo pacman -S $(cat ${zsh})
  check_fail
  show_info "Copying zshrc."
  cp -f ${zshrc} ${HOME}/.zshrc
  show_success "zsh installed."
}

zsh="${dir}/data/grsec.list"
function install_grsec {
  show_info "Installing grsecurity."
  sudo pacman -S $(cat ${grsec})
  check_fail
  show_success "Grsecurity-patched kernel installed."
  # need to set pax rules or enable learning mode
}

zsh="${dir}/data/utils.list"
function install_utils {
  show_info "Installing general utilities."
  sudo pacman -S $(cat ${utils})
  check_fail
  show_success "Utilities installed."

  # Enable tlp on laptops.
  show_question "Is this a laptop? (Y/n)"
  read -r response
  if [[ ${response} =~ ^([yY][eE][sS]|[yY])+$ ]]; then
    sudo systemctl enable tlp.service
    sudo systemctl start tlp.service
    check_fail
    show_success "tlp enabled."
  fi
}

android="${dir}/data/android.list"
function install_android {
  show_info "Installing tools for Android devices."
  sudo pacman -S $(cat ${android})
  check_fail
  show_success "Android tools installed."
}
