#! /bin/bash

dir="$(dirname "$0")"

gnome="${dir}/packages/gnome.list"
function install_gnome {
  show_header "Setting up GNOME desktop environment."
  check_installed $(cat ${gnome})
  check_fail
  show_success "GNOME installed."

  show_info "Putting things into place."
  if ! test ${DESKTOP_SESSION+x}; then
    export DESKTOP_SESSION="gnome"
  fi
  xdg-user-dirs-update
  sudo systemctl enable gdm.service

  show_info "Downloading 'No Topleft Hot Corner' GNOME extension."
  extensiondir=${HOME}/.local/share/gnome-shell/extensions
  mkdir -p "${extensiondir}"
  git clone https://github.com/HROMANO/nohotcorner \
    "${HOME}/.local/share/gnome-shell/extensions/nohotcorner@azuri.free.fr"
  git clone https://gitlab.com/rastersoft/desktop-icons-ng \
    "${HOME}/.local/share/gnome-shell/extensions/ding@rastersoft.com"

  show_info "Done."
}

cinnamon="${dir}/packages/cinnamon.list"
lightdmconf="/etc/lightdm/lightdm.conf"
redshiftconf="${dir}/configs/redshift.conf"
function install_cinnamon {
  show_header "Setting up cinnamon desktop environment."
  check_installed $(cat ${cinnamon})
  check_fail
  show_success "Cinnamon installed."

  show_info "Putting things into place."
  if ! test ${DESKTOP_SESSION+x}; then
    export DESKTOP_SESSION="cinnamon"
  fi

  # Get latitude and longitude using GeoClue2 for Redshift.
  show_info "Generating Redshift config."
  mkdir -p "${HOME}/.config/"
  local tmp
  local lat
  local lon
  tmp="$(/usr/lib/geoclue-2.0/demos/where-am-i -t 20)"
  lat="$(echo "$tmp" | \
         sed -n "s/^Latitude: \+\([-0-9\.]\+\)°$/\1/p" | head -n 1)"
  lon="$(echo "$tmp" | \
         sed -n "s/^Longitude: \+\([-0-9\.]\+\)°$/\1/p" | head -n 1)"
  cat "${redshiftconf}" | \
    sed -e "s,@latitude@,$lat,g" | \
    sed -e "s,@longitude@,$lon,g" > "${HOME}/.config/redshift.conf"

  xdg-user-dirs-update

  show_info "Setting up LightDM greeter."
  sudo sed -i \
    "s/^#greeter-hide-users=false/greeter-hide-users=false/g" \
    "${lightdmconf}"
  sudo sed -i \
    "s/^#greeter-session=.*/greeter-session=lightdm-gtk-greeter/g" \
    "${lightdmconf}"
  sudo systemctl enable lightdm.service
  show_info "Done."
}

function 02-desktop {
  show_question "Desktop: what do you want to install?"
  show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"

  options=("Back" "All" "GNOME" "Cinnamon")
  select option in "${options[@]}"; do
    case $option in
      "Back")
        break
        ;;
      "All")
        install_gnome
        install_cinnamon
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      "GNOME")
        install_gnome
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      "Cinnamon")
        install_cinnamon
        show_info "Main\n ${endbranch} Desktop (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}
