#! /bin/bash
#set -eu

dir="$(dirname "$0")"

gnome="${dir}/packages/gnome.list"
function install_gnome {
  show_info "Setting up GNOME desktop environment."
  sudo pacman -S $(cat ${gnome})
  check_fail
  show_success "GNOME installed."

  show_info "Putting things into place."
  sudo systemctl enable gdm.service
  show_info "Done."
}

cinnamon="${dir}/packages/cinnamon.list"
function install_cinnamon {
  show_info "Setting up cinnamon desktop environment."
  sudo pacman -S $(cat ${cinnamon})
  check_fail
  show_success "Cinnamon installed."
  
  show_info "Putting things into place."
  sudo systemctl enable lightdm.service
  show_info "Done."
}

function install_desktop {
  availabledesktops=("GNOME" "Cinnamon")
  show_question "Which desktop environment do you want?"
  select reply in "${availabledesktops[@]}"; do
    case $reply in 
      "GNOME")
        show_info "$reply selected."
        install_gnome
        break
        ;;
      "Cinnamon")
        show_info "$reply selected."
        install_cinnamon
        break
        ;;
      *) 
        echo "invalid option"
        break
        ;;
    esac
  done
}
