#! /bin/bash
set -eu

dir="$(dirname "$0")"

networking="${dir}/packages/network.list"
function install_network {
  show_info "Set up networking."
  sudo pacman -S $(cat ${networking})
  check_fail
  show_success "Applications installed."

  show_info "Setting up MAC address randomization."
  echo "" >> ${nmconf}
  echo "## Trying built-in MAC Address randomization" >> ${nmconf}
  echo "[connection]" >> ${nmconf}
  echo "wifi.cloned-mac-address=random" >> ${nmconf}
  echo "ethernet.cloned-mac-address=random" >> ${nmconf}
  sudo systemctl restart NetworkManager

  show_info "Enabling ufw."
  sudo ufw enable

  show_info "Enabling and start tor service."
  sudo systemctl enable tor
  sudo systemctl start tor

  show_info "Enabling local hostname resolution in Avahi."
  oldhostsline="hosts: files mymachines resolve \[!UNAVAIL=return\] dns myhostname"
  newhostsline="hosts: files mymachines mdns_minimal \[NOTFOUND=return\] resolve \[!UNAVAIL=return\] dns myhostname"
  sudo sed -i "s/${oldhostsline}/${newhostsline}/g" /etc/nsswitch.conf
  sudo sed -i "/${oldhostsline}/s/${oldhostsline}/${newhostsline}/g" /etc/nsswitch.conf
  sudo systemctl enable avahi-daemon.service
  sudo systemctl start avahi-daemon.service
}

