#! /bin/bash
set -eu

dir="$(dirname "$0")"

networking="${dir}/data/network.list"
nmconf="/etc/NetworkManager/NetworkManager.conf"
function install_network {
  show_info "Set up networking."
  sudo pacman -S $(cat ${networking})
  check_fail
  show_success "Applications installed."

  show_info "Setting up MAC address randomization."
  echo "" >> ${nmconf}
  echo "## Trying built-in MAC Address randomization" >> ${nmconf}
  echo "[connection]" >> ${nmconf}
  echo "wifi.cloned-mac-address=random" >> ${nmconf}
  echo "ethernet.cloned-mac-address=random" >> ${nmconf}
  sudo systemctl restart NetworkManager

  show_info "Enabling ufw."
  sudo ufw enable

  show_info "Enabling and start tor service."
  sudo systemctl start tor
  sudo systemctl enable tor
}

