#! /bin/bash
#set -eu

dir="$(dirname "$0")"

android="${dir}/packages/android.list"
function install_android {
  show_header "Installing tools for Android devices."
  check_installed $(cat ${android})
  check_fail
  show_success "Android tools installed."
}

apps="${dir}/packages/apps.list"
mpvconfig="${dir}/configs/mpv.conf"
function install_apps {
  show_header "Installing desktop applications."
  check_installed $(cat ${apps})
  check_fail
  show_success "Applications installed."

  show_info "Copying mpv config."
  mkdir -p ${HOME}/.config/mpv
  cp -f ${mpvconfig} ${HOME}/.config/mpv
}

codecs="${dir}/packages/codecs.list"
function install_codecs {
  show_header "Installing codecs."
  check_installed $(cat ${codecs})
  check_fail
  show_success "Codecs installed."
}

dev="${dir}/packages/dev.list"
npmrc="${dir}/dotfiles/npmrc"
function install_dev {
  show_header "Installing languages and editors for development."
  check_installed $(cat ${dev})
  check_fail
  show_success "Languages and editors installed."

  show_info "Installing dotfiles."
  cp -f ${npmrc} ${HOME}/.npmrc
  show_success "Dotfiles installed."
}

extra="${dir}/packages/apps.list"
function install_extra {
  show_header "Installing extra desktop applications."
  check_installed $(cat ${extra})
  check_fail
  show_success "Extra applications installed."
}

games="${dir}/packages/games.list"
function install_games {
  show_header "Installing game emulators."
  check_installed $(cat ${games})
  check_fail
  show_success "Emulators installed."
}

kvm="${dir}/packages/kvm.list"
function install_kvm {
  show_header "Installing KVM."
  check_installed $(cat ${kvm})
  check_fail
  show_success "KVM installed."

  show_info "Adding `whoami` to kvm and libvirt groups."
  sudo usermod -aG kvm,libvirt $(whoami)

  sudo systemctl enable libvirtd
  sudo systemctl start libvirtd
}

kvmguest="${dir}/packages/kvm-guest.list"
mkinitcpioconf="/etc/mkinitcpio.conf"
function install_kvm_guest {
  if grep "^flags.*\ hypervisor" /proc/cpuinfo >/dev/null 2>&1; then
    show_header "Installing tools for KVM guests."
    check_installed $(cat ${kvmguest})
    check_fail
    show_success "KVM installed."

    show_info "Adding virtio modules to initramfs."
    virtiomodules="virtio virtio_pci virtio_blk virtio_net virtio_ring"
    if test "$(grep "^MODULES=.*${virtiomodules}.*" ${mkinitcpioconf})"; then
      show_info "Virtio modules already specified in ${mkinitcpioconf}."
    else
      mkinitcpiomodules=$(sed -n "s/^MODULES=\"\(.*\)\"/\1 ${virtiomodules}/p" ${mkinitcpioconf} | sed -e "s/^[[:space:]]//g")
      sudo sed -i "s/^MODULES=\".*\"/MODULES=\"${mkinitcpiomodules}\"/" ${mkinitcpioconf}
      show_info "Rebuilding kernel(s)"
      sudo mkinitcpio -p linux
    fi

    sudo systemctl enable qemu-ga.service
    sudo systemctl enable spice-vdagentd.service
  else
    show_warning "Not running on a virtualized machine. Skipping."
  fi
}

torbrowser_path="~/.local/share/tor-browser"
function install_torbrowser {
  show_header "Installing tor browser."
  gpg --keyserver pool.sks-keyservers.net --recv-keys 0x4E2C6E8793298290
  
  torbrowser_version=6.5.2
  torbrowser_url=https://www.torproject.org/dist/torbrowser
  arch=`uname -m`
  if [ ${arch:-2} = "86" ]; then
    torbrowser_package=tor-browser-linux32-${torbrowser_version}_en-US.tar.xz
  elif [ ${arch:-2} = "64" ]; then
    torbrowser_package=tor-browser-linux64-${torbrowser_version}_en-US.tar.xz
  fi

  wget ${torbrowser_url}/${torbrowser_version}/${torbrowser_package}
  wget ${torbrowser_url}/${torbrowser_version}/${torbrowser_package}.asc
  gpg --verify ${torbrowser_package}.asc ${torbrowser_package}
  tar xf ${torbrowser_package}
  mv tor-browser_en-US ${torbrowser_path}
  cd ${torbrowser_path}
  ./start-tor-browser.desktop --register-app
  chmod -x ~/.local/share/applications/start-tor-browser.desktop
  # sed -i "s/^Icon=.*/Icon=browser-tor/g" ~/.local/share/applications/start-tor-browser.desktop
}

vim="${dir}/packages/vim.list"
vimrc="${dir}/dotfiles/vimrc"
function install_vim {
  show_header "Installing vim and vim plugins."
  check_installed $(cat ${vim})
  check_fail
  show_success "Vim and vim plugins installed."

  show_info "Installing vimrc."
  cp -f ${vimrc} ${HOME}/.vimrc
  show_success "vimrc installed."
}

virtualbox="${dir}/packages/virtualbox.list"
function install_virtualbox {
  show_header "Installing VirtualBox."
  check_installed $(cat ${virtualbox})
  check_fail
  show_success "VirtualBox installed."

  if getent group vboxusers; then
    show_info "Adding $(whoami) to vboxusers group."
    sudo usermod -aG vboxusers $(whoami)
  fi
}

virtualboxguest="${dir}/packages/virtualbox-guest.list"
function install_virtualbox_guest {
  if grep "^flags.*\ hypervisor" /proc/cpuinfo >/dev/null 2>&1; then
    show_header "Installing packages for VirtualBox guests."
    check_installed $(cat ${virtualboxguest})
    check_fail
    show_success "VirtualBox guest packages installed."
  else
    show_warning "Not running on a virtualized machine. Skipping."
  fi
}

function 03-packages {
  show_question "Applications: what do you want to install?"
  show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"

  options=("Back" "All" "Android tools" "General applications" "Codecs" \
           "Development" "Extra applications" "Emulators" "KVM (host)" \
           "KVM (guest)" "Install Tor browser" "Vim" "VirtualBox (host)" \
           "VirtualBox (guest)")
  select option in "${options[@]}"; do
    case $option in
      "Back")
        break
        ;;
      "All")
        install_android
        install_apps
        install_codecs
        install_dev
        install_extra
        install_games
        install_kvm
        install_kvm_guest
        install_torbrowser
        install_vim
        install_virtualbox
        install_virtualbox_guest
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Android tools")
        install_android
        show_info "Main\n ${endbranch} Misc (Hit ENTER to see options again.)"
        ;;
      "General applications")
        install_apps
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Codecs")
        install_codecs
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Development")
        install_dev
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Extra applications")
        install_extra
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Emulators")
        install_games
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "KVM (host)")
        install_kvm
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "KVM (guest)")
        install_kvm_guest
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Install Tor browser")
        install_torbrowser
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "Vim")
        install_vim
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "VirtualBox (host)")
        install_virtualbox
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      "VirtualBox (guest)")
        install_virtualbox_guest
        show_info "Main\n ${endbranch} Apps (Hit ENTER to see options again.)"
        ;;
      *)
        show_warning "Invalid option."
        ;;
    esac
  done
}
