#! /bin/bash
set -eu

dir="$(dirname "$0")"

function install_arc_gtk {
  git clone https://github.com/euphonia/arc-theme arc-theme
  cd arc-theme
  npm install
  ./autogen.sh --prefix=/usr
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf arc-theme
}

function install_adapta_gtk {
  git clone https://github.com/euphonia/Adapta adapta-gtk-theme
  cd adapta-gtk-theme
  ./autogen.sh \
    --prefix=/usr \
    --with-selection_color=#0097A7 \
    --with-second_selection_color=#00ACC1 \
    --with-accent_color=#00ACC1 \
    --with-suggestion_color=#0097A7 \
    --enable-parallel
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf adapta-gtk-theme
}

numix_folders="$dir/configs/numix-folders"
function install_numix_icons {
  git clone https://github.com/numixproject/numix-folders
  git clone https://github.com/numixproject/numix-icon-theme
  git clone https://github.com/numixproject/numix-icon-theme-circle
  git clone https://github.com/numixproject/numix-icon-theme-square

  sudo rsync -Prad --delete-excluded \
    numix-icon-theme/Numix/ \
    /usr/share/icons/Numix/
  sudo rsync -Prad --delete-excluded \
    numix-icon-theme-circle/Numix-Circle/ \
    /usr/share/icons/Numix-Circle/
  sudo rsync -Prad --delete-excluded \
    numix-icon-theme-square/Numix-Square/ \
    /usr/share/icons/Numix-Square/

  cp "$numix_folders" ~/.config/
  sudo ./numix-folders/numix-folders
  rm -rf numix-folders
  rm -rf numix-icon-theme
  rm -rf numix-icon-theme-circle
  rm -rf numix-icon-theme-square
}

function install_papirus_icons {
  git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

  sudo rsync -Prad --delete-excluded \
    papirus-icon-theme/ePapirus/ \
    /usr/share/icons/ePapirus/
  sudo rsync -Prad --delete-excluded \
    papirus-icon-theme/Papirus/ \
    /usr/share/icons/Papirus/
  sudo rsync -Prad --delete-excluded \
    papirus-icon-theme/Papirus-Dark/ \
    /usr/share/icons/Papirus-Dark/
  sudo rsync -Prad --delete-excluded \
    papirus-icon-theme/Papirus-Light/ \
    /usr/share/icons/Papirus-Light/

  rm -rf papirus-icon-theme
}

function set_lightdm_theme {
  if pacman -Qs lighdm-gtk-greeter > /dev/null; then
    sed -i "s/^#theme-name=$/theme-name=Arc-Dark/g" \
      /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "s/^#theme-name=$/icon-theme=Papirus-Dark/g" \
      /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "s/^#font-name=$/font-name=Noto Sans/g" \
      /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "s/^#xft-hintstyle=$/xfg-hintstyle=slight/g" \
      /etc/lightdm/lightdm-gtk-greeter.conf
  fi
}
