#! /bin/bash
set -eu

dir="$(dirname "$0")"

themes="${dir}/data/themes.list"
function install_theme_deps {
  show_info "Installing theme dependencies."
  sudo pacman -S $(cat ${themes})
  show_success "Theme dependencies installed."
}

function install_arc_gtk {
  git clone https://github.com/pseudorook/arc-theme arc-theme
  cd arc-theme
  npm install
  ./autogen.sh --prefix=/usr
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf arc-theme
}

function install_adapta_gtk {
  git clone https://github.com/pseudorook/Adapta adapta-gtk-theme
  cd adapta-gtk-theme
  ./autogen.sh \
    --prefix=/usr \
    --with-selection_color=#0097A7 \
    --with-second_selection_color=#00ACC1 \
    --with-accent_color=#00ACC1 \
    --with-suggestion_color=#0097A7 \
    --enable-parallel
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf adapta-gtk-theme
}

papirussrc="papirus-icon-theme"
icondest="/usr/share/icons"
function install_papirus_icons {
  git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/ePapirus/ 
    ${icondest}/ePapirus/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus/ \
    ${icondest}/Papirus/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus-Dark/ \
    ${icondest}/Papirus-Dark/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus-Light/ \
    ${icondest}/Papirus-Light/

  rm -rf ${papirussrc}
}

qt5ctconf="${dir}/configs/qt5ct.conf"
pkgbuilddir="${HOME}/.pkgbuild"
function set_qtcompat {
  show_info "Building qt5-styleplugins."
  mkdir -p ${pkgbuilddir}
  cd ${pkgbuilddir}
  wget https://aur.archlinux.org/cgit/aur.git/snapshot/qt5-styleplugins.tar.gz
  tar xf ${pkgbuilddir}/qt5-styleplugins.tar.gz
  cd qt5-styleplugins
  makepkg -si
  show_success "qt5-styleplugins built and installed."
  cd ${dir}

  show_info "Copying qt5ct config."
  mkdir -p ${HOME}/.config/qt5ct
  cp -f ${qt5ctconf} ${HOME}/.config/qt5ct
  show_success "qt5ct config opied."
}
