#! /bin/bash
set -eu

dir="$(dirname "$0")"

function install_arc_gtk {
  git clone https://github.com/pseudorook/arc-theme arc-theme
  cd arc-theme
  npm install
  ./autogen.sh --prefix=/usr
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf arc-theme
}

function install_adapta_gtk {
  git clone https://github.com/pseudorook/Adapta adapta-gtk-theme
  cd adapta-gtk-theme
  ./autogen.sh \
    --prefix=/usr \
    --with-selection_color=#0097A7 \
    --with-second_selection_color=#00ACC1 \
    --with-accent_color=#00ACC1 \
    --with-suggestion_color=#0097A7 \
    --enable-parallel
  make -j`nproc`
  sudo make install
  cd ..
  rm -rf adapta-gtk-theme
}

papirussrc="papirus-icon-theme"
icondest="/usr/share/icons"
function install_papirus_icons {
  git clone https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/ePapirus/ 
    ${icondest}/ePapirus/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus/ \
    ${icondest}/Papirus/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus-Dark/ \
    ${icondest}/Papirus-Dark/

  sudo rsync -Prad --delete-excluded \
    ${papirussrc}/Papirus-Light/ \
    ${icondest}/Papirus-Light/

  rm -rf ${papirussrc}
}

lightdmconf="/etc/lightdm/lightdm-gtk-greeter.conf"
function set_lightdm_theme {
  if pacman -Qs lighdm-gtk-greeter > /dev/null; then
    sudo sed -i "s/^#theme-name=$/theme-name=Arc-Dark/g" ${lightdmconf}
    sudo sed -i "s/^#icon-theme=$/icon-theme=Papirus-Dark/g" ${lightdmconf}
    if pacman -Qs noto-fonts > /dev/null; then
      sudo sed -i "s/^#font-name=$/font-name=Noto Sans/g" ${lightdmconf}
    fi
    sudo sed -i "s/^#xft-hintstyle=$/xft-hintstyle=slight/g" ${lightdmconf}
  fi
}
