#! /bin/bash
set -eu

dir="$(dirname "$0")"

# Set gvfs metadata
# Disable xdg PUBLIC and TEMPLATE
# Stop pulseaudio ringing
# Set dconf settings
# Pick themes (gnome, cinnamon, lightdm, etc.)
# Download scripts (submodule) and add to path

lightdmconf="/etc/lightdm/lightdm-gtk-greeter.conf"
function set_lightdm_theme {
  if pacman -Qs lighdm-gtk-greeter > /dev/null; then
    sudo sed -i "s/^#theme-name=$/theme-name=Arc-Dark/g" ${lightdmconf}
    sudo sed -i "s/^#icon-theme=$/icon-theme=Papirus-Dark/g" ${lightdmconf}
    if pacman -Qs noto-fonts > /dev/null; then
      sudo sed -i "s/^#font-name=$/font-name=Noto Sans/g" ${lightdmconf}
    fi
    sudo sed -i "s/^#xft-hintstyle=$/xft-hintstyle=slight/g" ${lightdmconf}
  fi
}
