#! /bin/bash
set -eu

dir="$(dirname "$0")"

# Set dconf settings
# Pick themes (gnome, cinnamon, lightdm, etc.)
# Download scripts (submodule) and add to path

icontheme="Papirus-Dark"
xdgdefaultconf="/etc/xdg/user-dirs.defaults"
function set_icon_theme {
  gsettings set org.cinnamon.desktop.interface icon-theme "'${icontheme}'"
  gsettings set org.gnome.desktop.interface icon-theme "'${icontheme}'"

  gvfs-set-attribute ${HOME}/Projects/ -t string \
    metadata::custom-icon-name folder-development
  gvfs-set-attribute ${HOME}/Sync/ -t string \
    metadata::custom-icon-name folder-cloud

  sudo sed -i "s/*TEMPLATES/#TEMPLATES/g" ${xdgdefaultconf}
  sudo sed -i "s/*PUBLICSHARE/#PUBLICSHARE/g" ${xdgdefaultconf}
}

gtktheme="Arc-Dark"
function set_gtk_theme {
  if [ ${DESKTOP_SESSION} = "cinnamon" ]; then
    gsettings set org.cinnamon.desktop.interface gtk-theme "'${gtktheme}'"
    gsettings set org.cinnamon.desktop.wm.preferences theme "'${gtktheme}'"
    gsettings set org.cinnamon.theme name "'${gtktheme}'"
  elif [ ${DESKTOP_SESSION} = "gnome" ]; then
    gsettings set org.gnome.desktop.wm.preferences theme "'${gtktheme}'"
    gsettings set org.gnome.desktop.interface gtk-theme "'${gtktheme}'"
  fi
}

gtktheme="Arc-Dark"
lightdmconf="/etc/lightdm/lightdm-gtk-greeter.conf"
function set_lightdm_theme {
  if pacman -Qs lighdm-gtk-greeter > /dev/null; then
    sudo sed -i "s/^#theme-name=$/theme-name=${gtktheme}/g" ${lightdmconf}
    sudo sed -i "s/^#icon-theme=$/icon-theme=${icontheme}/g" ${lightdmconf}
    if pacman -Qs noto-fonts > /dev/null; then
      sudo sed -i "s/^#font-name=$/font-name=Noto Sans/g" ${lightdmconf}
    fi
    sudo sed -i "s/^#xft-hintstyle=$/xft-hintstyle=slight/g" ${lightdmconf}
  fi
}

grubconfig="/etc/default/grub"
function invert_brightness {
  oldline=$(cat ${grubconfig} | grep ^GRUB_CMDLINE_LINUX=)
  bootparams=$(echo ${oldline} | sed -n "s/^GRUB_CMDLINE_LINUX=\"\(.*\)\"/\1/p")
  if [[ ${bootparams} =~ "i915.invert_brightness=1" ]]; then
    show_info "Brightness already inverted. Skipping."
  else
    sed -i "s|${bootparams}|${bootparams} i915.invert_brightness=1|g" ${grubconfig}
    sed -i "\|^GRUB_CMDLINE_LINUX=| a\#${oldline}" ${grubconfig}
    show_success "Brightness inverted."
  fi
}

pulseconfig="/etc/pulse/default.pa"
function disable_pulseaudio_suspend {
  show_info "Disabling suspend on PulseAudio when sinks/sources idle."
  if [ -f ${pulseconfig} ]; then
    sed -i "s/^load-module module-suspend-on-idle$/#load-module module-suspend-on-idle/g" ${pulseconfig}
  else
    show_warning "PuleAudio config file missing. Exiting."
  fi
}
