#! /bin/bash
set -eu

dir="$(dirname "$0")"

# Set gvfs metadata
# Disable xdg PUBLIC and TEMPLATE
# Stop pulseaudio ringing
# Set dconf settings
# Pick themes (gnome, cinnamon, lightdm, etc.)
# Enable tor andset up tor browser.
# Download scripts (submodule) and add to path
