#! /bin/bash
set -eu

dir="$(dirname "$0")"

#
# Fancy color output
#

show_error() {
  echo -e "\033[1;31m$@\033[m" 1>&2
}
show_info() {
  echo -e "\033[1;32m$@\033[0m"
}
show_warning() {
  echo -e "\033[1;33m$@\033[0m"
}
show_question() {
  echo -e "\033[1;34m$@\033[0m"
}
show_success() {
  echo -e "\033[1;35m$@\033[0m"
}
show_header() {
  echo -e "\033[1;36m$@\033[0m"
}
show_listitem() {
  echo -e "\033[0;37m$@\033[0m"
}


#
# Source the functions
#

. $dir/functions/00-check
. $dir/functions/01-base
. $dir/functions/01-misc
. $dir/functions/02-desktop
. $dir/functions/03-network
. $dir/functions/03-packages
. $dir/functions/04-themes
. $dir/functions/05-personal


#
# Just testing
#

show_question "question"
show_error "error"
show_warning "warning"
show_success "success"
show_info "info"
show_listitem "listitem"
show_header "header"


#
# Check if dependencies are installed and if network is working
#

install_dependencies
check_network


#
# Install base packages and miscellaneous extras
#

# install_base

# install_zsh
# install_grsec
# install_utils
# install_laptop
# install_android


#
# Install a desktop environment
#

# install_desktop


#
# Install packages and set up network configuration
#

# install_apps
# install_codecs
# install_dev
# install_games
# install_kvm
# install_kvm_guest
# install_virtualbox
# install_virtualbox_guest

# install_network


#
# Install GTK themes
#

# install_theme_deps
# install_arc_gtk
# install_adapta_gtk
# install_fonts
# install_papirus_icons
# set_qtcompat


#
# Add my personal settings
#

# set_noto_fonts
# set_icon_theme
# set_gtk_theme
# set_lightdm_theme
# set_dark_gtk
# import_cinnamon_dconf
# import_gnome_dconf
# import_apps_dconf
# invert_brightness
# disable_pulseaudio_suspend
